### ISSUE TITLE
Upload failure

### ISSUE THREAD

**Issue by paolo-tonella** [ASQ-USI/ASQ#159]
When I try to uplodad a new version of my presentation on the server, I get the error message:

&lt;html&gt;&lt;body&gt;&lt;h1&gt;504 Gateway Time-out&lt;/h1&gt;
The server didn&#39;t respond in time.
&lt;/body&gt;&lt;/html&gt;

The command that I have prompted was just copy-pasted from the ASQ web page.

**Comment by triglian** [comment]
We resolved the problem in person
